server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao_client_id}
            client-secret: ${kakao_client_secret}
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            redirect-uri: http://${blogdomain}/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  datasource:
    # driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/blog?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${blogip}:3306/blog
    username: ${blogdbid}
    password: ${blogdbpassword}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

  jackson:
    serialization:
      fail-on-empty-beans: false
