# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: mincho CD

on:
  workflow_run:
    workflows: ["mincho CI"]
    branches: ["main"]
    types: ["completed"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: ./build/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./build/
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.KEY }}
      - name: SCP transfer
        run: scp *.jar ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/cicd
      - name: Server Download
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/compose-server/minchoboard/spring/source
            sudo git pull
            docker-compose stop
            docker-compose up -d --build
