name: mincho CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
        #uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        #with:
        #arguments: build
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./build/ # or path/to/artifact

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Downloaded artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: ./build/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./build/

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./build/"
          target: "/home/${{ secrets.USERNAME }}/compose-server/minchoboard/spring"

      - name: Server Up
        uses: appleboy/ssh-action@master
        env:
          BLOGIP: ${{ secrets.BLOGIP }}
          BLOGDBPASSWORD: ${{ secrets.BLOGDBPASSWORD }}
          BLOGDBID: ${{ secrets.BLOGDBID }}
          BLOGDOMAIN: ${{ secrets.BLOGDOMAIN }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: BLOGIP, BLOGDBPASSWORD, BLOGDBID, BLOGDOMAIN, KAKAO_CLIENT_ID, KAKAO_CLIENT_SECRET
          script: |
            #putty로 접속시 서버에 있는 환경변수가 잘 적용이 되지만, 
            #github action사용시 서버에 있는 환경변수가 적용이 안되서 spring boot 프로젝트를 실행하면 에러가 난다.
            #그래서 github action에서 환경변수를 생성하고, 서버에 접속후 export를 해준다.
            export blogip=$BLOGIP
            export blogdbpassword=$BLOGDBPASSWORD
            export blogdbid=$BLOGDBID
            export blogdomain=$BLOGDOMAIN
            export kakao_client_id=$KAKAO_CLIENT_ID
            export kakao_client_secret=$KAKAO_CLIENT_SECRET
            cd ~/compose-server/minchoboard/spring
            docker-compose stop
            docker-compose up -d --build
            docker image prune
