name: mincho CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
        #uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        #with:
        #arguments: build
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./build/ # or path/to/artifact

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Downloaded artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: ./build/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./build/

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./build/libs/*.jar"
          target: "/home/${{ secrets.USERNAME }}/compose-server/minchoboard/spring"

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.KEY }}
          
      - name: Add remote server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          
      - name: Execute remote commands
        run: |
          ssh -v ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd ~/compose-server/minchoboard/spring"
          ssh -v ${{ secrets.USERNAME }}@${{ secrets.HOST }} "docker-compose stop"
          ssh -v ${{ secrets.USERNAME }}@${{ secrets.HOST }} "docker-compose up -d --build"
          ssh -v ${{ secrets.USERNAME }}@${{ secrets.HOST }} "docker image prune"
