name: mincho CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
        #uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        #with:
        #arguments: build
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./build/ # or path/to/artifact

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Downloaded artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: ./build/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./build/

      - name: Docker Stop Before Downloading
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/compose-server/minchoboard/spring

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./build/libs/*.jar"
          target: "/home/${{ secrets.USERNAME }}/compose-server/minchoboard/spring"
          
      - name: Server Up
        uses: appleboy/ssh-action@master
        env:
          BLOGIP: ${{ secrets.BLOGIP }}
          BLOGDBPASSWORD: ${{ secrets.BLOGDBPASSWORD }}
          BLOGDBID: ${{ secrets.BLOGDBID }}
          BLOGDOMAIN: ${{ secrets.BLOGDOMAIN }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: BLOGIP, BLOGDBPASSWORD, BLOGDBID, BLOGDOMAIN, KAKAO_CLIENT_ID, KAKAO_CLIENT_SECRET
          script: |
            export BLOGIP=$BLOGIP
            export BLOGDBPASSWORD=$BLOGDBPASSWORD
            export BLOGDBID=$BLOGDBID
            export BLOGDOMAIN=$BLOGDOMAIN
            export KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID
            export KAKAO_CLIENT_SECRET=$KAKAO_CLIENT_SECRET
            env
            #source ~/.bashrc
            cd ~/compose-server/minchoboard/spring
            docker-compose stop
            docker-compose up -d --build
            docker image prune
